SpicyXPractice/Models/Chef.cs
using SpicyXPractice.Models.Common;
using System.ComponentModel.DataAnnotations.Schema;

namespace SpicyXPractice.Models
{
    public class Chef:BaseEntity
    {
        public string FullName { get; set; }
        public string Position  { get; set; }
        public string ImageUrl { get; set; }
        [NotMapped]
        public IFormFile? Image { get; set; }    
        public string Fcblink { get; set; }
        public string twtlink { get; set; }
        public string gglink { get; set; }
        public string linkedin { get; set; }

    }
}

SpicyXPractice/Models/Common/BaseEntity.cs
namespace SpicyXPractice.Models.Common
{
    public class BaseEntity
    {
        public int Id { get; set; }
    }
}

SpicyXPractice/ViewModels/ChefCreateVM.cs
using System.ComponentModel.DataAnnotations.Schema;

namespace SpicyXPractice.ViewModels
{
    public class ChefCreateVM
    {
        public string FullName { get; set; }
        public string Position { get; set; }
       
        [NotMapped]
        public IFormFile? Image { get; set; }
        public string Fcblink { get; set; }
        public string twtlink { get; set; }
        public string gglink { get; set; }
        public string linkedin { get; set; }
    }
}

SpicyXPractice/ViewModels/ChefUpdateVM.cs
using System.ComponentModel.DataAnnotations.Schema;

namespace SpicyXPractice.ViewModels
{
    public class ChefUpdateVM
    {
        public int Id { get; set; }
        public string FullName { get; set; }
        public string Position { get; set; }
        public string ImageUrl { get; set; }
        [NotMapped]
        public IFormFile? Image { get; set; }
        public string Fcblink { get; set; }
        public string twtlink { get; set; }
        public string gglink { get; set; }
        public string linkedin { get; set; }
    }
}

SpicyXPractice/Areas/admin/Controllers/ChefController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using SpicyXPractice.DAL;
using SpicyXPractice.Models;
using SpicyXPractice.ViewModels;
using System.ComponentModel.Design;

namespace SpicyXPractice.Areas.admin.Controllers
{
    [Area("admin")]
    public class ChefController : Controller
    {
        private readonly AppDbContext _context;
        private readonly IWebHostEnvironment _env;

        public ChefController(AppDbContext context, IWebHostEnvironment env)
        {
            _context = context;
            _env = env;
        }

        public IActionResult Index()
        {
            var chefs = _context.Chefs.ToList();
            return View(chefs);
        }
        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Create(ChefCreateVM vm)
        {
            if (!ModelState.IsValid)
            {
                return View(vm);
            }
            var isExisted = await _context.Chefs.AnyAsync(x => x.FullName.ToLower().Contains(vm.FullName.ToLower()));
            if (!isExisted)
            {
                ModelState.AddModelError("FullName", "Bu name artiq movcuddur");
            }
            if (!vm.Image.ContentType.Contains("image"))
            {
                ModelState.AddModelError("Image", "Seklin tipi yanlisdir");
            }
            if (vm.Image.Length < 1024 * 1024)
            {
                ModelState.AddModelError("Image", "Sekil 1mb dan artiq olmalidir");
            }
            string filename = Guid.NewGuid() + vm.Image.FileName;
            string path = Path.Combine(_env.WebRootPath, "admin", "images",filename);
            using (FileStream stream = new(path, FileMode.Create))
            {
                await vm.Image.CopyToAsync(stream);
            }
            Chef chef = new Chef()
            {
                FullName = vm.FullName,
                ImageUrl = filename,
                Position = vm.Position,
                Fcblink = vm.Fcblink,
                twtlink = vm.twtlink,
                gglink = vm.gglink,
                linkedin = vm.linkedin,

            };

            await _context.Chefs.AddAsync(chef);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index");
        }
        [HttpGet]
        public async Task<IActionResult> Update(int id)
        {
            if (id <= 0) return BadRequest();
            var existed = await _context.Chefs.SingleOrDefaultAsync(x => x.Id == id);
            if (existed != null) return NotFound();
            ChefUpdateVM vm = new ChefUpdateVM()
            {
                Id = existed.Id,
                FullName = existed.FullName,
                ImageUrl = existed.ImageUrl,
                Position = existed.Position,
                Fcblink = existed.Fcblink,
                twtlink = existed.twtlink,
                gglink = existed.gglink,
                linkedin = existed.linkedin,
            };

            return View(existed);
        }
        [HttpPost]
        public async Task<IActionResult> Update(ChefUpdateVM vm)
        {
            if (!ModelState.IsValid)
            {
                return View(vm);
            }
            var existed = await _context.Chefs.FirstOrDefaultAsync(x => x.Id == vm.Id);
            if (existed != null) return NotFound();
            var isExisted = await _context.Chefs.AnyAsync(x => x.FullName.ToLower().Contains(vm.FullName.ToLower()) && x.Id != vm.Id);
            if (!isExisted)
            {
                ModelState.AddModelError("FullName", "Bu chef movcuddur");
            }
            if (vm.Image is not null)
            {

                string filename = Guid.NewGuid() + vm.Image.FileName;
                string path = Path.Combine(_env.ContentRootPath, "wwwroot", "admin", "images", filename);
                if (System.IO.File.Exists(path + "/" + vm.ImageUrl))
                {
                    System.IO.File.Delete(path + "/" + vm.ImageUrl);
                }
                using (FileStream stream = new(path + "/" + filename, FileMode.Create))
                {
                    await vm.Image.CopyToAsync(stream);
                }
                filename = existed.ImageUrl;
            }
            existed.FullName = vm.FullName;
            existed.Position=vm.Position;
            existed.twtlink = vm.twtlink;
            existed.Fcblink= vm.Fcblink;
            existed.gglink= vm.gglink;
            existed.linkedin= vm.linkedin;

            _context.Chefs.Update(existed);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index");

        }
        public async Task<IActionResult> Delete(int id)
        {
            if (id <= 0) return BadRequest();
            var existed= await _context.Chefs.FirstOrDefaultAsync(x=>x.Id == id);
            if(existed == null) return NotFound();
            string path = Path.Combine(_env.ContentRootPath, "assets/image",existed.ImageUrl);
            if(System.IO.File.Exists(path))
            {
                System.IO.File.Delete(path);
            }

            _context.Chefs.Remove(existed);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index");  
        }
    }
}

SpicyXPractice/Areas/admin/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;

namespace SpicyXPractice.Areas.admin.Controllers
{
    [Area("Admin")]
    public class HomeController : Controller
    {

        public IActionResult Index()
        {
            return View();
        }
    }
}

SpicyXPractice/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;

namespace SpicyXPractice.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

SpicyXPractice/Areas/admin/Views/Chef/Create.cshtml
@model ChefCreateVM

<div class="col-md-6 grid-margin stretch-card">
    <div class="card">
        <div class="card-body">
            <h4 class="card-title">Create</h4>
            <p class="card-description">
                Chefs
            </p>
            <form class="forms-sample" enctype="multipart/form-data" method="post">
                <div class="form-group">
                    <label asp-for="FullName">FullName</label>
                    <input asp-for="FullName" class="form-control" placeholder="FullName">
                    <span class="text-danger" asp-validation-for="FullName" ></span>
                </div> 
                 <div class="form-group">
                    <label asp-for="Position">Position</label>
                    <input asp-for="Position" class="form-control" placeholder="Position">
                    <span class="text-danger" asp-validation-for="Position" ></span>
                </div> 
                 <div class="form-group">
                    <label asp-for="linkedin">Linkedin</label>
                    <input asp-for="linkedin" class="form-control" placeholder="Linkedin">
                    <span class="text-danger" asp-validation-for="linkedin" ></span>
                </div> 
                 <div class="form-group">
                    <label asp-for="Fcblink">Facebook</label>
                    <input asp-for="Fcblink" class="form-control" placeholder="Facebook">
                    <span class="text-danger" asp-validation-for="Fcblink" ></span>
                </div>
                <div class="form-group">
                    <label asp-for="twtlink">Twitter</label>
                    <input asp-for="twtlink" class="form-control" placeholder="Twitter">
                    <span class="text-danger" asp-validation-for="twtlink"></span>
                </div>
                 <div class="form-group">
                    <label asp-for="gglink">FullName</label>
                    <input asp-for="gglink" class="form-control" placeholder="FullName">
                    <span class="text-danger" asp-validation-for="gglink"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Image">Image</label>
                    <input asp-for="Image" class="form-control" placeholder="Image">
                    <span class="text-danger" asp-validation-for="Image"></span>
                </div>
                <div class="form-check form-check-flat form-check-primary">
                    <label class="form-check-label">
                        <input type="checkbox" class="form-check-input">
                        Remember me
                    </label>
                </div>
                <button type="submit" class="btn btn-primary me-2">Submit</button>
                <a type="button" asp-action="index" asp-controller="Chef" class="btn btn-light">Cancel</a>
            </form>
        </div>
    </div>
</div>

SpicyXPractice/Areas/admin/Views/Chef/Index.cshtml
@model List<Chef>

@{
    int count = 0;
}
<div class="col-lg-12 grid-margin stretch-card">
    <div class="card">
        <div class="card-body">
            <h1 class="card-title .h1">Team</h1>

            <a asp-action="create" class="btn btn-success">
                Create Team
            </a>

            <div class="table-responsive">
                <table class="table table-striped">
                    <thead>
                        <tr>
                            <th>
                                FullName
                            </th>
                            <th>
                                Position
                            </th>
                            <th>
                                Facebook
                            </th>
                            <th>
                                Twitter
                            </th>
                            <th>
                                Linkedin
                            </th>
                            <th>
                                Google
                            </th>
                            <th>
                                Image
                            </th>
                            <th>
                                Settings
                            </th>
                        </tr>
                    </thead>
                    <tbody>

                        @foreach (var item in Model)
                        {
                            count++;
                            <tr>
                                <td>
                                    <i class="@item.ImageUrl"></i>
                                </td>
                                <td>
                                    @item.FullName
                                </td>
                                <td>
                                    @item.Position
                                </td>
                                <td>
                                    @item.Fcblink
                                </td>
                                <td>
                                    @item.twtlink
                                </td>
                                <td>
                                    @item.gglink
                                </td>
                                <td>
                                    @item.linkedin
                                </td>
                                <td>
                                    <div class="btn-group">
                                        <a asp-action="Delete" asp-route-id="@item.Id" class="btn-sm btn btn-danger">
                                            <i class="mdi mdi-delete-forever btn-icon-primary">
                                            </i>
                                        </a>
                                        <a asp-action="Update" asp-route-id="@item.Id" class="btn-sm btn btn-warning">
                                            <i class="mdi mdi-lead-pencil btn-icon-primary">
                                            </i>
                                        </a>
                                        <a asp-action="Detail" asp-route-id="@item.Id" class="btn-sm btn btn-primary">
                                            <i class="mdi mdi-open-in-new btn-icon-primary">
                                            </i>
                                        </a>
                                    </div>
                                </td>
                            </tr>
                        }

                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

SpicyXPractice/Areas/admin/Views/Chef/Update.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

SpicyXPractice/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>SpicyX | Home</title>

    <!-- Favicon -->
    <link rel="shortcut icon" href="~/assets/img/favicon.ico" type="image/x-icon">

    <!-- Font awesome -->
    <link href="~/assets/css/font-awesome.css" rel="stylesheet">
    <!-- Bootstrap -->
    <link href="~/assets/css/bootstrap.css" rel="stylesheet">
    <!-- Slick slider -->
    <link rel="stylesheet" type="text/css" href="~/assets/css/slick.css">
    <!-- Date Picker -->
    <link rel="stylesheet" type="text/css" href="~/assets/css/bootstrap-datepicker.css">
    <!-- Fancybox slider -->
    <link rel="stylesheet" href="~/assets/css/jquery.fancybox.css" type="text/css" media="screen" />
    <!-- Theme color -->
    <link id="switcher" href="~/assets/css/theme-color/default-theme.css" rel="stylesheet">

    <!-- Main style sheet -->
    <link href="~/assets/style.css" rel="stylesheet">


    <!-- Google Fonts -->
    <link href='https://fonts.googleapis.com/css?family=Tangerine' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Open+Sans' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Prata' rel='stylesheet' type='text/css'>


    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>
<body>
    <!-- Pre Loader -->
    <div id="aa-preloader-area">
        <div class="mu-preloader">
            <img src="~/assets/img/preloader.gif" alt=" loader img">
        </div>
    </div>
    <!--START SCROLL TOP BUTTON -->
    <a class="scrollToTop" href="#">
        <i class="fa fa-angle-up"></i>
        <span>Top</span>
    </a>
    <!-- END SCROLL TOP BUTTON -->
    <!-- Start header section -->
    <header id="mu-header">
        <nav class="navbar navbar-default mu-main-navbar" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <!-- FOR MOBILE VIEW COLLAPSED BUTTON -->
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <!-- LOGO -->
                    <a class="navbar-brand" href="index.html"><img src="~/assets/img/logo.png" alt="Logo img"></a>
                </div>
                <div id="navbar" class="navbar-collapse collapse">
                    <ul id="top-menu" class="nav navbar-nav navbar-right mu-main-nav">
                        <li><a href="#mu-slider">HOME</a></li>
                        <li><a href="#mu-about-us">ABOUT US</a></li>
                        <li><a href="#mu-restaurant-menu">MENU</a></li>
                        <li><a href="#mu-reservation">RESERVATION</a></li>
                        <li><a href="#mu-gallery">GALLERY</a></li>
                        <li><a href="#mu-chef">OUR TEAM</a></li>
                        <li><a href="#mu-latest-news">BLOG</a></li>
                        <li><a href="#mu-contact">CONTACT</a></li>
                        <li class="dropdown">
                            <a class="dropdown-toggle" data-toggle="dropdown" href="blog-archive.html">PAGE <span class="caret"></span></a>
                            <ul class="dropdown-menu" role="menu">
                                <li><a href="blog-archive.html">BLOG</a></li>
                                <li><a href="blog-single.html">BLOG DETAILS</a></li>
                                <li><a href="404.html">404 PAGE</a></li>
                            </ul>
                        </li>
                    </ul>
                </div><!--/.nav-collapse -->
            </div>
        </nav>
    </header>
    <!-- End header section -->
    @RenderBody()
    <!-- Start Footer -->
    <footer id="mu-footer">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <div class="mu-footer-area">
                        <div class="mu-footer-social">
                            <a href="#"><span class="fa fa-facebook"></span></a>
                            <a href="#"><span class="fa fa-twitter"></span></a>
                            <a href="#"><span class="fa fa-google-plus"></span></a>
                            <a href="#"><span class="fa fa-linkedin"></span></a>
                            <a href="#"><span class="fa fa-youtube"></span></a>
                        </div>
                        <div class="mu-footer-copyright">
                            <p>Designed by <a rel="nofollow" href="http://www.markups.io/">MarkUps.io</a></p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </footer>
    <!-- End Footer -->
    <!-- jQuery library -->
    <script src="~/assets/js/jquery.min.js"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="~/assets/js/bootstrap.js"></script>
    <!-- Slick slider -->
    <script type="text/javascript" src="~/assets/js/slick.js"></script>
    <!-- Counter -->
    <script type="text/javascript" src="~/assets/js/waypoints.js"></script>
    <script type="text/javascript" src="~/assets/js/jquery.counterup.js"></script>
    <!-- Date Picker -->
    <script type="text/javascript" src="~/assets/js/bootstrap-datepicker.js"></script>
    <!-- Mixit slider -->
    <script type="text/javascript" src="~/assets/js/jquery.mixitup.js"></script>
    <!-- Add fancyBox -->
    <script type="text/javascript" src="~/assets/js/jquery.fancybox.pack.js"></script>

    <!-- Custom js -->
    <script src="~/assets/js/custom.js"></script>

</body>
</html>